inhibit_all_warnings!
# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj 'OnWorld'

pod "AFNetworking", "~> 2.0"
pod "BFTask-Extras"
pod "MagicalRecord"
pod "HexColors", "~> 2.2.1"

post_install do |installer|
    installer.project.targets.each do |target|
        puts target.name
    end
end

